ALTER TABLE TAPIGEN.TE_TEMPLATES
 DROP PRIMARY KEY CASCADE
/

DROP TABLE TAPIGEN.TE_TEMPLATES CASCADE CONSTRAINTS
/

CREATE TABLE TAPIGEN.TE_TEMPLATES
(
  NAME           VARCHAR2(300 BYTE)                 NULL,
  TEMPLATE       CLOB                               NULL,
  DESCRIPTION    VARCHAR2(300 BYTE)                 NULL,
  CREATED_BY     VARCHAR2(100 BYTE)             DEFAULT user                  NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  MODIFIED_BY    VARCHAR2(100 BYTE)             DEFAULT user                  NOT NULL,
  MODIFIED_DATE  DATE                           DEFAULT SYSDATE               NOT NULL
)
TABLESPACE USERS
/


CREATE UNIQUE INDEX TAPIGEN.TE_TEMPLATES_PK ON TAPIGEN.TE_TEMPLATES
(NAME)
TABLESPACE USERS
/


ALTER TABLE TAPIGEN.TE_TEMPLATES ADD (
  CONSTRAINT TE_TEMPLATES_PK
 PRIMARY KEY
 (NAME)
    USING INDEX 
    TABLESPACE USERS)
/


